version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t my-app .

artifacts:
  files:
    - '**/*'
