name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  devsecops:
    name: Run CI/CD Pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run tfsec (Terraform Security)
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        working_directory: ./terraform

    - name: Build Docker image
      run: docker build -t your-image-name:latest .

    - name: Run Trivy scan on Docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: your-image-name:latest
        format: table

    - name: Set up Kubeconfig for kubectl
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Apply Sealed Secrets
      run: kubectl apply -f k8s/sealed-secret.yaml

    - name: Deploy Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
