name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest
    steps:

    # 1️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3️⃣ Build Docker image
    - name: Build Docker image
      run: docker build -t node-app ./node-app

    # 4️⃣ Trivy Scan
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: node-app
        format: table
        exit-code: 0
        severity: CRITICAL,HIGH

    # 5️⃣ tfsec for Terraform scanning
    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
